version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    networks:
      - tomagram-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tomagram
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - tomagram-net
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tomagram

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - tomagram-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - tomagram-net
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: elasticsearch
    networks:
      - tomagram-net
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"

  tomagram-redis:
    image: redis:latest
    container_name: tomagram-redis
    networks:
      - tomagram-net
    ports:
      - "6379:6379"

  tomagram-service:
    build:
      context: ./tomagram
      dockerfile: Dockerfile
    container_name: tomagram-service
    networks:
      - tomagram-net
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - mongodb
      - kafka
      - elasticsearch

  feed-service:
    build:
      context: ./feed-service
      dockerfile: Dockerfile
    container_name: feed-service
    networks:
      - tomagram-net
    ports:
      - "8085:8085"
    depends_on:
      - tomagram-redis
    environment:
      REDIS_PORT: 6379

networks:
  tomagram-net:
    driver: bridge
