version: '3.8'
services:
  app:
    image: orcaabs/tomagram-service-a:latest
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy  # Wait until MySQL is healthy before starting
      mongodb:
        condition: service_started
    restart: on-failure  # Restart the app if it fails initially
    networks:
      - container

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Use a secure password for production
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_DATABASE: "posts_db"
    ports:
      - "3306:3306"
    volumes:
      - container-mysql:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - container
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      retries: 5
      timeout: 10s
      start_period: 30s
      interval: 10s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - container

networks:
  container:
    driver: bridge

volumes:
  container-mysql:
    driver: local
